Ext.define('Infosys_web.model.Pedidos', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'id'},
        {name: 'num_pedido'},
        {name: 'id_formula'},
        {name: 'nom_formula'},
        {name: 'codigo'},
        {name: 'cantidad', decimalPrecision:4},
        {name: 'abono'},
        {name: 'tip_documento'},
        {name: 'nom_documento'},
        {name: 'fecha_doc', type:'date',dateFormat:"Y-m-d"},        
        {name: 'id_cliente'},
        {name: 'nombre_cliente'},
        {name: 'telefono'},
        {name: 'id_sucursal'},        
        {name: 'rut_cliente'},
        {name: 'id_vendedor'},
        {name: 'nom_vendedor'},
        {name: 'nom_producto'},
        {name: 'nombre_producto'},
        {name: 'fecha_pedido', type:'date',dateFormat:"Y-m-d"},
        {name: 'hora_pedido'},
        {name: 'fecha_venc', type:'date',dateFormat:"Y-m-d"},
        {name: 'fecha_despacho', type:'date',dateFormat:"Y-m-d"},
        {name: 'fecha_elabora', type:'date',dateFormat:"Y-m-d"},
        {name: 'hora_despacho'},
        {name: 'id_pago'},
        {name: 'descuento'},
        {name: 'neto'},
        {name: 'iva'},
        {name: 'total'},
        {name: 'id_tipopedido'},
        {name: 'estado'},
        {name: 'situacionpedido'},
        {name: 'nom_bodega'},
        {name: 'id_bodega'},
        {name: 'id_producto'},
        {name: 'cantidad_requiere_receta'}
         
       
    ]
});