Ext.define('Infosys_web.model.Producto', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'id'},
        {name: 'id_existencia'},
        {name: 'nombre'},
        {name: 'codigo'},
        {name: 'p_ult_compra'},
        {name: 'p_may_compra'},
        {name: 'p_venta', decimalPrecision:3},
        {name: 'p_neto', decimalPrecision:3},
        {name: 'p_costo', decimalPrecision:3},
        {name: 'cantidad_real', decimalPrecision:4},
        {name: 'cantidad', decimalPrecision:4},
        {name: 'nom_uni_medida'},
        {name: 'id_marca'},
        {name: 'nom_marca'},
        {name: 'id_uni_medida'},
        {name: 'nom_ubi_prod'},
        {name: 'id_ubi_prod'},
        {name: 'p_promedio'},
        {name: 'nom_familia'},
        {name: 'id_familia'},
        {name: 'id_bodega'},
        {name: 'id_agrupacion'},
        {name: 'id_subfamilia'},
        {name: 'foto'},
        {name: 'nom_agrupacion'},
        {name: 'nom_subfamilia'},
        {name: 'stock'},
        {name: 'stock_critico'},
        {name: 'diasvencimiento'},
        {name: 'nom_bodega'},
        {name: 'u_lote'},
        {name: 'clasificacion'},    
        {name: 'requiere_receta'},        
    ]
});